config/routes.rb
Rails.application.routes.draw do

    resources :places, only: [:new, :create, :edit, :update]
    
    root to: 'places#index'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :place
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
    has_many :addresses, dependent: :destroy, inverse_of: :place
    accepts_nested_attributes_for :addresses, allow_destroy: true,
                              reject_if: ->(attrs) { attrs['city'].blank? || attrs['street'].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    
    def index
        @places = Place.all
    end
    
    def new
        @place = Place.new
    end
    
    def create
        @place = Place.new(place_params)
        
        if @place.save
            redirect_to root_path
        else
            render :new
        end
    end
    
    def edit
      @place = Place.find(params[:id])
    end
    
    def update
      @place = Place.find(params[:id])
      if @place.update_attributes(place_params)
        redirect_to root_path
      else
        render :edit
      end
    end

    private
    
    def place_params
        params.require(:place).permit(:title, addresses_attributes: [:id, :city, :street, :_destroy])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favorites</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_address_fields.html.erb
<div class="nested-fields">
    <%= f.label :city %>
    <%= f.text_field :city %>
     
    <%= f.label :street %>
    <%= f.text_field :street %>
    
    <%= link_to_remove_association "Remove address", f %>
</div>

app/views/places/_form.html.erb
<%= render 'shared/errors', object: @place %>

<%= form_for @place do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <p><strong>Addresses:</strong></p>
        <div id='addresses'>
            <%= f.fields_for :addresses do |address| %>
                <%= render 'address_fields', f: address %>
            <% end %>
            <div class='links'>
                <%= link_to_add_association 'Add address', f, :addresses %>
            </div>
            <p class='count'>Total: <span><%= @place.addresses.count %></span></p>
        </div>
    </div>
    <%= f.submit %>
<% end %>

app/views/places/_place.html.erb
<li>
    <strong><%= place.title %></strong> | <%= link_to 'Edit place', edit_place_path(place) %></br>
    
    <% if place.addresses.any? %>
        Addresses:
        <ul>
            <% place.addresses.each do |address| %>
                <li>
                    <%= address.city %>, <%= address.street %>
                </li>
            <% end %>
        </ul>
    <% end %>
    </br>
</li>

app/views/places/edit.html.erb
<h1>Edit place</h1>
<%= render 'form' %>

app/views/places/index.html.erb
<h1>Favorite Places</h1>
<p><%= link_to "Add new place", new_place_path %></p>
<ul>
    <%= render @places %>
</ul>

app/views/places/new.html.erb
<h1>Add place</h1>
<%= render 'form' %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div>
        <strong>
            <%= pluralize(object.errors.count, 'error') %> were found
        </strong>
        
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li>
                    <%= msg %>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>